package dev.igordesouza.orthos.plugin.generator

/**
 * Generates a holder containing a build-time canary.
 */
object GeneratedCanaryHolder {

    fun generate(): String {
        val canary = (Math.random() * Int.MAX_VALUE).toInt()

        return """
            package dev.igordesouza.orthos.runtime.generated

            /**
             * Generated bytecode canary holder.
             */
            object CanaryHolder {
                const val EXPECTED = $canary
                const val RUNTIME = $canary
            }
        """.trimIndent()
    }
}
