package dev.igordesouza.orthos.plugin.util

import org.objectweb.asm.*
import org.objectweb.asm.util.Textifier
import org.objectweb.asm.util.TraceMethodVisitor
import java.io.PrintWriter
import java.io.StringWriter

/**
 * Utility class for inspecting and asserting ASM-generated bytecode.
 */
object BytecodeInspector {

    fun containsField(bytes: ByteArray, fieldName: String): Boolean {
        var found = false
        ClassReader(bytes).accept(object : ClassVisitor(Opcodes.ASM9) {
            override fun visitField(
                access: Int,
                name: String,
                descriptor: String,
                signature: String?,
                value: Any?
            ): FieldVisitor? {
                if (name == fieldName) found = true
                return null
            }
        }, 0)
        return found
    }

    fun containsMethod(bytes: ByteArray, methodName: String): Boolean {
        var found = false
        ClassReader(bytes).accept(object : ClassVisitor(Opcodes.ASM9) {
            override fun visitMethod(
                access: Int,
                name: String,
                descriptor: String,
                signature: String?,
                exceptions: Array<out String>?
            ): MethodVisitor? {
                if (name == methodName) found = true
                return null
            }
        }, 0)
        return found
    }

    fun containsMethodInvocation(
        bytes: ByteArray,
        owner: String,
        methodName: String
    ): Boolean {
        var found = false
        ClassReader(bytes).accept(object : ClassVisitor(Opcodes.ASM9) {
            override fun visitMethod(
                access: Int,
                name: String,
                descriptor: String,
                signature: String?,
                exceptions: Array<out String>?
            ): MethodVisitor {
                return object : MethodVisitor(Opcodes.ASM9) {
                    override fun visitMethodInsn(
                        opcode: Int,
                        ownerName: String,
                        name: String,
                        descriptor: String,
                        isInterface: Boolean
                    ) {
                        if (ownerName == owner && name == methodName) {
                            found = true
                        }
                    }
                }
            }
        }, 0)
        return found
    }

    fun disassemble(bytes: ByteArray): List<String> {
        val instructions = mutableListOf<String>()
        val reader = ClassReader(bytes)

        reader.accept(object : ClassVisitor(Opcodes.ASM9) {
            override fun visitMethod(
                access: Int,
                name: String,
                descriptor: String,
                signature: String?,
                exceptions: Array<out String>?
            ): MethodVisitor {
                val textifier = Textifier()
                val traceVisitor = TraceMethodVisitor(textifier)

                return object : MethodVisitor(Opcodes.ASM9, traceVisitor) {
                    override fun visitEnd() {
                        val sw = StringWriter()
                        textifier.print(PrintWriter(sw))
                        instructions += sw.toString().lines()
                    }
                }
            }
        }, 0)

        return instructions
    }
}
